name = "Foxxo Demon Pack"
author = "hexagonelle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90337a9dfa77c77ddf3cae45cb4f949d169c8aff345aae99f00e14b3187d06ae"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
